In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv("flight_random_1million.csv",
    dtype={'cancellation_code':'str'},
    low_memory=False)

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 35 columns):
 #   Column               Non-Null Count    Dtype
---  ------               --------------    -----
 0   year                 1000000 non-null  int64
 1   month                1000000 non-null  int64
 2   day_of_month         1000000 non-null  int64
 3   day_of_week          1000000 non-null  int64
 4   fl_date              1000000 non-null  str
 5   op_unique_carrier    1000000 non-null  str
 6   op_carrier_fl_num    999999 non-null   float64
 7   origin               1000000 non-null  str
 8   origin_city_name     1000000 non-null  str
 9   origin_state_nm      1000000 non-null  str
 10  dest                 1000000 non-null  str
 11  dest_city_name       1000000 non-null  str
 12  dest_state_nm        1000000 non-null  str
 13  crs_dep_time         1000000 non-null  int64
 14  dep_time             986927 non-null   float64
 15  dep_delay            986882 non-null   float64
 16  taxi_out             986499 non-null   float64
 17  wheels_off           986499 non-null   float64
 18  wheels_on            986173 non-null   float64
 19  taxi_in              986173 non-null   float64
 20  crs_arr_time         1000000 non-null  int64
 21  arr_time             986174 non-null   float64
 22  arr_delay            984033 non-null   float64
 23  cancelled            1000000 non-null  int64
 24  cancellation_code    13608 non-null    str
 25  diverted             1000000 non-null  int64
 26  crs_elapsed_time     1000000 non-null  float64
 27  actual_elapsed_time  984033 non-null   float64
 28  air_time             984033 non-null   float64
 29  distance             1000000 non-null  float64
 30  carrier_delay        1000000 non-null  int64
 31  weather_delay        1000000 non-null  int64
 32  nas_delay            1000000 non-null  int64
 33  security_delay       1000000 non-null  int64
 34  late_aircraft_delay  1000000 non-null  int64
dtypes: float64(13), int64(13), str(9)
memory usage: 324.9 MB

In [4]:
df.columns

Index(['year', 'month', 'day_of_month', 'day_of_week', 'fl_date',
       'op_unique_carrier', 'op_carrier_fl_num', 'origin', 'origin_city_name',
       'origin_state_nm', 'dest', 'dest_city_name', 'dest_state_nm',
       'crs_dep_time', 'dep_time', 'dep_delay', 'taxi_out', 'wheels_off',
       'wheels_on', 'taxi_in', 'crs_arr_time', 'arr_time', 'arr_delay',
       'cancelled', 'cancellation_code', 'diverted', 'crs_elapsed_time',
       'actual_elapsed_time', 'air_time', 'distance', 'carrier_delay',
       'weather_delay', 'nas_delay', 'security_delay', 'late_aircraft_delay'],
      dtype='str')

In [5]:
# checking for dataset if it is balanced or not
df['month'].value_counts().sort_index()

month
1     77578
2     73508
3     83133
4     81816
5     86255
6     85899
7     90449
8     86939
9     82186
10    87256
11    81470
12    83511
Name: count, dtype: int64

In [6]:
df['op_unique_carrier'].value_counts()

op_unique_carrier
WN    200799
DL    142792
AA    138835
UA    107444
OO    105392
YX     42465
MQ     39773
NK     36964
AS     34705
B6     33913
OH     31940
F9     29342
9E     28064
G4     16412
HA     11160
Name: count, dtype: int64

In [7]:
df['origin'].value_counts().head(20)

origin
ATL    48656
DFW    44306
DEN    43812
ORD    39385
CLT    30411
PHX    27257
LAX    27240
LAS    26621
SEA    23107
LGA    22951
MCO    22637
BOS    20181
DCA    19690
SFO    19048
DTW    18573
EWR    18299
MSP    17923
JFK    17379
IAH    16573
SLC    15831
Name: count, dtype: int64

In [8]:
df.isna().sum().sort_values(ascending=False)

cancellation_code      986392
actual_elapsed_time     15967
arr_delay               15967
air_time                15967
wheels_on               13827
taxi_in                 13827
arr_time                13826
wheels_off              13501
taxi_out                13501
dep_delay               13118
dep_time                13073
op_carrier_fl_num           1
day_of_month                0
year                        0
month                       0
dest                        0
origin_state_nm             0
fl_date                     0
day_of_week                 0
dest_state_nm               0
dest_city_name              0
crs_dep_time                0
op_unique_carrier           0
origin                      0
origin_city_name            0
crs_arr_time                0
cancelled                   0
crs_elapsed_time            0
diverted                    0
distance                    0
carrier_delay               0
weather_delay               0
nas_delay                   0
security_delay              0
late_aircraft_delay         0
dtype: int64

In [9]:
df[['cancelled', 'diverted']].value_counts()

cancelled  diverted
0          0           984033
1          0            13608
0          1             2359
Name: count, dtype: int64

In [10]:
# converting all the required column into proper formate datetime format for futher anaylsis
# in time column there is hour and minutes both so converted them in to_date time column
# in integer column there are only minutes are given so converted them into intergers

# -------- Time columns --------
time_cols = [
    'crs_dep_time',
    'dep_time',
    'wheels_off',
    'wheels_on',
    'crs_arr_time',
    'arr_time'
]

# Convert float -> Int64 -> string -> pad zeros
df[time_cols] = (
    df[time_cols]
    .astype('Int64')
    .astype(str)
    .apply(lambda x: x.str.zfill(4))
)

# Convert to datetime
for col in time_cols:
    df[col] = pd.to_datetime(
        df[col],
        format='%H%M',
        errors='coerce'
    )


# -------- Integer columns --------
int_cols = [
    'taxi_out',
    'taxi_in',
    'arr_delay',
    'distance',
    'crs_elapsed_time',
    'actual_elapsed_time',
]

df[int_cols] = df[int_cols].astype('Int64')

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 35 columns):
 #   Column               Non-Null Count    Dtype
---  ------               --------------    -----
 0   year                 1000000 non-null  int64
 1   month                1000000 non-null  int64
 2   day_of_month         1000000 non-null  int64
 3   day_of_week          1000000 non-null  int64
 4   fl_date              1000000 non-null  str
 5   op_unique_carrier    1000000 non-null  str
 6   op_carrier_fl_num    999999 non-null   float64
 7   origin               1000000 non-null  str
 8   origin_city_name     1000000 non-null  str
 9   origin_state_nm      1000000 non-null  str
 10  dest                 1000000 non-null  str
 11  dest_city_name       1000000 non-null  str
 12  dest_state_nm        1000000 non-null  str
 13  crs_dep_time         1000000 non-null  datetime64[us]
 14  dep_time             986811 non-null   datetime64[us]
 15  dep_delay            986882 non-null   float64
 16  taxi_out             986499 non-null   Int64
 17  wheels_off           986329 non-null   datetime64[us]
 18  wheels_on            985730 non-null   datetime64[us]
 19  taxi_in              986173 non-null   Int64
 20  crs_arr_time         1000000 non-null  datetime64[us]
 21  arr_time             985633 non-null   datetime64[us]
 22  arr_delay            984033 non-null   Int64
 23  cancelled            1000000 non-null  int64
 24  cancellation_code    13608 non-null    str
 25  diverted             1000000 non-null  int64
 26  crs_elapsed_time     1000000 non-null  Int64
 27  actual_elapsed_time  984033 non-null   Int64
 28  air_time             984033 non-null   float64
 29  distance             1000000 non-null  Int64
 30  carrier_delay        1000000 non-null  int64
 31  weather_delay        1000000 non-null  int64
 32  nas_delay            1000000 non-null  int64
 33  security_delay       1000000 non-null  int64
 34  late_aircraft_delay  1000000 non-null  int64
dtypes: Int64(6), datetime64[us](6), float64(3), int64(11), str(9)
memory usage: 330.6 MB

In [12]:
# flight date from int into datetime format
df['fl_date'] = pd.to_datetime(df['fl_date'], errors='coerce')

In [13]:
# carrier flight number into string
df['op_carrier_fl_num'] = df['op_carrier_fl_num'].astype(str)

In [14]:
# departure delay column from float into int
df['dep_delay'] = df['dep_delay'].astype("Int64")

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 35 columns):
 #   Column               Non-Null Count    Dtype
---  ------               --------------    -----
 0   year                 1000000 non-null  int64
 1   month                1000000 non-null  int64
 2   day_of_month         1000000 non-null  int64
 3   day_of_week          1000000 non-null  int64
 4   fl_date              1000000 non-null  datetime64[us]
 5   op_unique_carrier    1000000 non-null  str
 6   op_carrier_fl_num    999999 non-null   str
 7   origin               1000000 non-null  str
 8   origin_city_name     1000000 non-null  str
 9   origin_state_nm      1000000 non-null  str
 10  dest                 1000000 non-null  str
 11  dest_city_name       1000000 non-null  str
 12  dest_state_nm        1000000 non-null  str
 13  crs_dep_time         1000000 non-null  datetime64[us]
 14  dep_time             986811 non-null   datetime64[us]
 15  dep_delay            986882 non-null   Int64
 16  taxi_out             986499 non-null   Int64
 17  wheels_off           986329 non-null   datetime64[us]
 18  wheels_on            985730 non-null   datetime64[us]
 19  taxi_in              986173 non-null   Int64
 20  crs_arr_time         1000000 non-null  datetime64[us]
 21  arr_time             985633 non-null   datetime64[us]
 22  arr_delay            984033 non-null   Int64
 23  cancelled            1000000 non-null  int64
 24  cancellation_code    13608 non-null    str
 25  diverted             1000000 non-null  int64
 26  crs_elapsed_time     1000000 non-null  Int64
 27  actual_elapsed_time  984033 non-null   Int64
 28  air_time             984033 non-null   float64
 29  distance             1000000 non-null  Int64
 30  carrier_delay        1000000 non-null  int64
 31  weather_delay        1000000 non-null  int64
 32  nas_delay            1000000 non-null  int64
 33  security_delay       1000000 non-null  int64
 34  late_aircraft_delay  1000000 non-null  int64
dtypes: Int64(7), datetime64[us](7), float64(1), int64(11), str(9)
memory usage: 327.6 MB

In [16]:
df['year'].nunique()

1

In [17]:
# deleting the year column because every value is same
df = df.drop(columns = ['year'])

In [18]:
df['cancellation_code'].isnull().sum()

np.int64(986392)

In [19]:
# deleting the cancellation code column because there are more than 40 percent null values in it.
df = df.drop(columns = ['cancellation_code'])

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 33 columns):
 #   Column               Non-Null Count    Dtype
---  ------               --------------    -----
 0   month                1000000 non-null  int64
 1   day_of_month         1000000 non-null  int64
 2   day_of_week          1000000 non-null  int64
 3   fl_date              1000000 non-null  datetime64[us]
 4   op_unique_carrier    1000000 non-null  str
 5   op_carrier_fl_num    999999 non-null   str
 6   origin               1000000 non-null  str
 7   origin_city_name     1000000 non-null  str
 8   origin_state_nm      1000000 non-null  str
 9   dest                 1000000 non-null  str
 10  dest_city_name       1000000 non-null  str
 11  dest_state_nm        1000000 non-null  str
 12  crs_dep_time         1000000 non-null  datetime64[us]
 13  dep_time             986811 non-null   datetime64[us]
 14  dep_delay            986882 non-null   Int64
 15  taxi_out             986499 non-null   Int64
 16  wheels_off           986329 non-null   datetime64[us]
 17  wheels_on            985730 non-null   datetime64[us]
 18  taxi_in              986173 non-null   Int64
 19  crs_arr_time         1000000 non-null  datetime64[us]
 20  arr_time             985633 non-null   datetime64[us]
 21  arr_delay            984033 non-null   Int64
 22  cancelled            1000000 non-null  int64
 23  diverted             1000000 non-null  int64
 24  crs_elapsed_time     1000000 non-null  Int64
 25  actual_elapsed_time  984033 non-null   Int64
 26  air_time             984033 non-null   float64
 27  distance             1000000 non-null  Int64
 28  carrier_delay        1000000 non-null  int64
 29  weather_delay        1000000 non-null  int64
 30  nas_delay            1000000 non-null  int64
 31  security_delay       1000000 non-null  int64
 32  late_aircraft_delay  1000000 non-null  int64
dtypes: Int64(7), datetime64[us](7), float64(1), int64(10), str(8)
memory usage: 312.2 MB

In [21]:
df['arr_time'].head(20)

0    1900-01-01 11:39:00
1    1900-01-01 19:06:00
2    1900-01-01 10:42:00
3    1900-01-01 14:31:00
4    1900-01-01 15:09:00
5    1900-01-01 08:16:00
6    1900-01-01 11:58:00
7    1900-01-01 21:28:00
8    1900-01-01 09:37:00
9    1900-01-01 23:27:00
10   1900-01-01 17:43:00
11   1900-01-01 00:25:00
12   1900-01-01 08:05:00
13   1900-01-01 19:48:00
14   1900-01-01 17:07:00
15   1900-01-01 09:47:00
16   1900-01-01 17:50:00
17   1900-01-01 13:02:00
18   1900-01-01 16:00:00
19   1900-01-01 20:25:00
Name: arr_time, dtype: datetime64[us]

In [22]:
# changing the datatype of air time into proper foramt
df['air_time'] = df['air_time'].astype('Int64')

In [23]:
# checked for duplicate
df.duplicated().sum()

np.int64(0)

In [24]:
df.loc[(df['cancelled'] == 0) &  (df['diverted'] == 0)].isna().sum().sort_values(ascending=False)

arr_time               538
wheels_on              442
wheels_off             170
dep_time               115
op_carrier_fl_num        1
month                    0
origin                   0
op_unique_carrier        0
day_of_month             0
origin_state_nm          0
origin_city_name         0
dest                     0
dest_city_name           0
crs_dep_time             0
dest_state_nm            0
fl_date                  0
day_of_week              0
taxi_out                 0
dep_delay                0
taxi_in                  0
crs_arr_time             0
arr_delay                0
cancelled                0
diverted                 0
crs_elapsed_time         0
actual_elapsed_time      0
air_time                 0
distance                 0
carrier_delay            0
weather_delay            0
nas_delay                0
security_delay           0
late_aircraft_delay      0
dtype: int64

In [25]:
# checked for missised departure time
df.loc[(df['cancelled']==0) & (df['diverted']==0) & (df['dep_time'].isna()),
    ['crs_dep_time','dep_delay','taxi_out','wheels_off']].head(20)

              crs_dep_time  dep_delay  taxi_out          wheels_off
2144   1900-01-01 22:38:00         82        19 1900-01-01 00:19:00
7032   1900-01-01 23:59:00          1        15 1900-01-01 00:15:00
8287   1900-01-01 23:00:00         60        13 1900-01-01 00:13:00
10293  1900-01-01 19:00:00        300        50 1900-01-01 00:50:00
34540  1900-01-01 22:54:00         66        10 1900-01-01 00:10:00
36765  1900-01-01 23:59:00          1        14 1900-01-01 00:14:00
42056  1900-01-01 17:50:00        370        17 1900-01-01 00:17:00
54008  1900-01-01 23:59:00          1        19 1900-01-01 00:19:00
73308  1900-01-01 23:59:00          1        16 1900-01-01 00:16:00
75713  1900-01-01 00:06:00         -6        13 1900-01-01 00:13:00
76772  1900-01-01 22:52:00         68        14 1900-01-01 00:14:00
80624  1900-01-01 23:50:00         10        15 1900-01-01 00:15:00
92041  1900-01-01 23:50:00         10        16 1900-01-01 00:16:00
148664 1900-01-01 23:59:00          1        23 1900-01-01 00:23:00
174588 1900-01-01 22:20:00        100        16 1900-01-01 00:16:00
193392 1900-01-01 22:05:00        115        11 1900-01-01 00:11:00
222012 1900-01-01 23:14:00         46        16 1900-01-01 00:16:00
227417 1900-01-01 22:05:00        115        11 1900-01-01 00:11:00
228607 1900-01-01 23:59:00          1        14 1900-01-01 00:14:00
242066 1900-01-01 23:55:00          5        35 1900-01-01 00:35:00

In [26]:
mask = ((df['cancelled']==0) & (df['diverted']==0) & (df['dep_time'].isna()) & (df['crs_dep_time'].notna()) & (df['dep_delay'].notna()))

mask.sum()

np.int64(115)

In [27]:
# imputing the dep time with sheduled departure time + dep delay
mask = ((df['cancelled']==0) & (df['diverted']==0) & (df['dep_time'].isna()))

# Fill missing departure time
df.loc[mask, 'dep_time'] = (df.loc[mask, 'crs_dep_time'] + pd.to_timedelta(df.loc[mask, 'dep_delay'],unit='m'))

In [28]:
# cheked the departure time for normal flights
df.loc[(df['cancelled']==0) & (df['diverted']==0) & (df['dep_time'].isna())].shape[0]

0

In [29]:
# cheked for null wheels_off values
df.loc[(df['cancelled']==0) & (df['diverted']==0) & (df['wheels_off'].isna()),['dep_time','taxi_out']].head(20)

                  dep_time  taxi_out
5601   1900-01-01 23:50:00        10
5633   1900-01-01 23:49:00        11
5680   1900-01-01 23:48:00        12
14400  1900-01-01 23:31:00        29
22687  1900-01-01 23:47:00        13
29850  1900-01-01 23:42:00        18
31217  1900-01-01 23:52:00         8
48627  1900-01-01 23:11:00        49
81258  1900-01-01 23:45:00        15
98077  1900-01-01 23:48:00        12
103052 1900-01-01 23:49:00        11
104495 1900-01-01 23:49:00        11
112743 1900-01-01 23:41:00        19
119319 1900-01-01 23:31:00        29
125604 1900-01-01 23:29:00        31
144226 1900-01-01 23:18:00        42
144759 1900-01-01 23:43:00        17
156053 1900-01-01 23:51:00         9
159733 1900-01-01 23:47:00        13
164363 1900-01-01 23:44:00        16

In [30]:
mask = ((df['cancelled']==0) & (df['diverted']==0) & (df['wheels_off'].isna()) &(df['dep_time'].notna()) & (df['taxi_out'].notna()))

mask.sum()

np.int64(170)

In [31]:
# imputing the wheels_off values with (dep_time + taxi_out)
mask = ((df['cancelled']==0) & (df['diverted']==0) & (df['wheels_off'].isna()))

# Fill missing wheels_off
df.loc[mask, 'wheels_off'] = (df.loc[mask, 'dep_time'] + pd.to_timedelta(df.loc[mask, 'taxi_out'],unit='m'))

In [32]:
df.loc[(df['cancelled']==0) & (df['diverted']==0)].isna().sum().sort_values(ascending=False)

arr_time               538
wheels_on              442
op_carrier_fl_num        1
month                    0
day_of_month             0
op_unique_carrier        0
origin                   0
fl_date                  0
day_of_week              0
dest                     0
dest_city_name           0
dest_state_nm            0
crs_dep_time             0
dep_time                 0
dep_delay                0
origin_city_name         0
origin_state_nm          0
wheels_off               0
taxi_out                 0
taxi_in                  0
crs_arr_time             0
arr_delay                0
cancelled                0
diverted                 0
crs_elapsed_time         0
actual_elapsed_time      0
air_time                 0
distance                 0
carrier_delay            0
weather_delay            0
nas_delay                0
security_delay           0
late_aircraft_delay      0
dtype: int64

In [33]:
# checked for missing wheels_on time
df.loc[(df['cancelled']==0) & (df['diverted']==0) & (df['wheels_on'].isna()),['wheels_off','air_time']].head(20)

               wheels_off  air_time
2391  1900-01-01 22:58:00        62
6433  1900-01-01 23:00:00        60
8686  1900-01-01 23:09:00       171
9334  1900-01-01 22:09:00       111
10604 1900-01-01 22:13:00       167
11650 1900-01-01 23:35:00        25
13078 1900-01-01 22:49:00        71
13948 1900-01-01 23:11:00        49
14473 1900-01-01 18:30:00       210
18197 1900-01-01 22:52:00        68
28384 1900-01-01 20:13:00       107
29318 1900-01-01 22:54:00        66
34356 1900-01-01 23:32:00        28
34542 1900-01-01 21:29:00       151
34751 1900-01-01 23:03:00       117
35393 1900-01-01 21:58:00       122
37100 1900-01-01 22:38:00       202
38516 1900-01-01 18:11:00       229
38704 1900-01-01 23:05:00       115
39460 1900-01-01 22:46:00        74

In [34]:
mask = ((df['cancelled']==0) & (df['diverted']==0) & (df['wheels_on'].isna()) & (df['wheels_off'].notna()) & (df['air_time'].notna()))

mask.sum()

np.int64(442)

In [35]:
# imputing the wheels_on time using (wheels_off + air_time)
mask = ((df['cancelled']==0) & (df['diverted']==0) & (df['wheels_on'].isna()))

# Fill missing wheels_on
df.loc[mask, 'wheels_on'] = (df.loc[mask, 'wheels_off'] + pd.to_timedelta(df.loc[mask, 'air_time'],unit='m'))

In [36]:
df.loc[(df['cancelled']==0) & (df['diverted']==0)].isna().sum().sort_values(ascending=False)

arr_time               538
op_carrier_fl_num        1
month                    0
fl_date                  0
day_of_month             0
op_unique_carrier        0
origin                   0
origin_city_name         0
day_of_week              0
dest                     0
dest_city_name           0
dest_state_nm            0
crs_dep_time             0
dep_time                 0
dep_delay                0
taxi_out                 0
origin_state_nm          0
wheels_off               0
wheels_on                0
taxi_in                  0
crs_arr_time             0
arr_delay                0
cancelled                0
diverted                 0
crs_elapsed_time         0
actual_elapsed_time      0
air_time                 0
distance                 0
carrier_delay            0
weather_delay            0
nas_delay                0
security_delay           0
late_aircraft_delay      0
dtype: int64

In [37]:
mask = ((df['cancelled']==0) & (df['diverted']==0) & (df['arr_time'].isna()) & (df['wheels_on'].notna()) & (df['taxi_in'].notna()))

mask.sum()

np.int64(538)

In [38]:
# imputing arr_time missing values (wheels_on + taxi_in)
mask = ((df['cancelled']==0) & (df['diverted']==0) & (df['arr_time'].isna()))

# Fill missing arrival time
df.loc[mask, 'arr_time'] = (df.loc[mask, 'wheels_on'] + pd.to_timedelta(df.loc[mask, 'taxi_in'],unit='m'))

In [39]:
df.loc[(df['cancelled']==0) & (df['diverted']==0)].isna().sum().sort_values(ascending=False)

op_carrier_fl_num      1
month                  0
day_of_month           0
fl_date                0
day_of_week            0
op_unique_carrier      0
origin                 0
origin_city_name       0
origin_state_nm        0
dest                   0
dest_city_name         0
dest_state_nm          0
crs_dep_time           0
dep_time               0
dep_delay              0
taxi_out               0
wheels_off             0
wheels_on              0
taxi_in                0
crs_arr_time           0
arr_time               0
arr_delay              0
cancelled              0
diverted               0
crs_elapsed_time       0
actual_elapsed_time    0
air_time               0
distance               0
carrier_delay          0
weather_delay          0
nas_delay              0
security_delay         0
late_aircraft_delay    0
dtype: int64

In [40]:
(df.loc[(df['cancelled']==0) &(df['diverted']==0),'actual_elapsed_time'] - (df['taxi_out'] + df['air_time'] + df['taxi_in'])).value_counts().head(20)

0    984033
Name: count, dtype: Int64

In [41]:
# checking for diverted missing values
df.loc[df['diverted']==1].isna().sum().sort_values(ascending=False)

actual_elapsed_time    2359
arr_delay              2359
air_time               2359
arr_time                221
wheels_on               220
taxi_in                 219
month                     0
day_of_month              0
day_of_week               0
dest                      0
dest_city_name            0
fl_date                   0
op_unique_carrier         0
op_carrier_fl_num         0
origin                    0
origin_city_name          0
origin_state_nm           0
wheels_off                0
taxi_out                  0
dep_delay                 0
dep_time                  0
crs_dep_time              0
dest_state_nm             0
crs_arr_time              0
cancelled                 0
crs_elapsed_time          0
diverted                  0
distance                  0
carrier_delay             0
weather_delay             0
nas_delay                 0
security_delay            0
late_aircraft_delay       0
dtype: int64

In [42]:
df.loc[(df['diverted']==1) & (df['wheels_on'].isna()),['wheels_off','air_time','arr_time','taxi_in']].head(20)

               wheels_off  air_time arr_time  taxi_in
1197  1900-01-01 16:17:00      <NA>      NaT     <NA>
1773  1900-01-01 10:17:00      <NA>      NaT     <NA>
2169  1900-01-01 15:25:00      <NA>      NaT     <NA>
6865  1900-01-01 21:50:00      <NA>      NaT     <NA>
8561  1900-01-01 16:22:00      <NA>      NaT     <NA>
16825 1900-01-01 21:07:00      <NA>      NaT     <NA>
16925 1900-01-01 20:14:00      <NA>      NaT     <NA>
24517 1900-01-01 18:01:00      <NA>      NaT     <NA>
28236 1900-01-01 11:29:00      <NA>      NaT     <NA>
30048 1900-01-01 15:44:00      <NA>      NaT     <NA>
30502 1900-01-01 15:06:00      <NA>      NaT     <NA>
33105 1900-01-01 20:14:00      <NA>      NaT     <NA>
33298 1900-01-01 11:55:00      <NA>      NaT     <NA>
39839 1900-01-01 06:02:00      <NA>      NaT     <NA>
41247 1900-01-01 01:18:00      <NA>      NaT     <NA>
44907 1900-01-01 14:33:00      <NA>      NaT     <NA>
46401 1900-01-01 14:24:00      <NA>      NaT     <NA>
52389 1900-01-01 19:31:00      <NA>      NaT     <NA>
56820 1900-01-01 08:14:00      <NA>      NaT     <NA>
58338 1900-01-01 08:55:00      <NA>      NaT     <NA>

In [43]:
# adding route column for better understanding
df['route'] = df['origin'] + " → " + df['dest']

In [44]:
df['route'].nunique()

6588

In [45]:
# Actual early arrival delay values
df['arrived_early'] = np.where((df['arr_delay'].notna()) & (df['arr_delay'] < 0),df['arr_delay'],np.nan)

# Actual late arrival delay values
df['arrived_late'] = np.where((df['arr_delay'].notna()) & (df['arr_delay'] > 0),df['arr_delay'],np.nan)

In [46]:
# Create arrival status column
df['arrival_status'] = 'Unknown'

# Cancelled flights
df.loc[df['cancelled'] == 1, 'arrival_status'] = 'Cancelled'

# Diverted flights
df.loc[df['diverted'] == 1, 'arrival_status'] = 'Diverted'

# Normal flights classification
df.loc[(df['cancelled']==0) & (df['diverted']==0) & (df['arr_delay'] < 0),'arrival_status'] = 'Arrived Early'

df.loc[(df['cancelled']==0) & (df['diverted']==0) & (df['arr_delay'] == 0),'arrival_status'] = 'Arrived On Time'

df.loc[(df['cancelled']==0) & (df['diverted']==0) & (df['arr_delay'] > 0),'arrival_status'] = 'Arrived Late'

In [47]:
df['arrival_status'].unique()

<ArrowStringArray>
['Arrived Early', 'Arrived Late', 'Cancelled', 'Arrived On Time', 'Diverted']
Length: 5, dtype: str

In [48]:
# Actual early departure delay values
df['departed_early'] = np.where((df['dep_delay'].notna()) & (df['dep_delay'] < 0),df['dep_delay'],np.nan)

# Actual late departure delay values
df['departed_late'] = np.where((df['dep_delay'].notna()) & (df['dep_delay'] > 0),df['dep_delay'],np.nan)

In [49]:
# Create departure status column
df['departure_status'] = 'Unknown'

# Cancelled flights
df.loc[df['cancelled'] == 1, 'departure_status'] = 'Cancelled'

# Diverted flights
df.loc[df['diverted'] == 1, 'departure_status'] = 'Diverted'

# Normal flights classification
df.loc[(df['cancelled']==0) & (df['diverted']==0) & (df['dep_delay'] < 0),'departure_status'] = 'departed Early'

df.loc[(df['cancelled']==0) & (df['diverted']==0) & (df['dep_delay'] == 0),'departure_status'] = 'departed On Time'

df.loc[(df['cancelled']==0) & (df['diverted']==0) & (df['dep_delay'] > 0),'departure_status'] = 'departed Late'

In [50]:
df['departure_status'].unique()

<ArrowStringArray>
['departed Early', 'departed Late', 'Cancelled', 'departed On Time',
 'Diverted']
Length: 5, dtype: str

In [51]:
print(df[['arrival_status']].value_counts())
print()
print(df[['departure_status']].value_counts())
print()
print(df[['arrived_early']].count())
print()
print(df[['arrived_late']].count())
print()
print(df[['departed_early']].count())
print()
print(df[['departed_late']].count())

arrival_status
Arrived Early      609665
Arrived Late       356910
Arrived On Time     17458
Cancelled           13608
Diverted             2359
Name: count, dtype: int64

departure_status
departed Early      575134
departed Late       366323
departed On Time     42576
Cancelled            13608
Diverted              2359
Name: count, dtype: int64

arrived_early    609665
dtype: int64

arrived_late    356910
dtype: int64

departed_early    576240
dtype: int64

departed_late    367960
dtype: int64

In [52]:
# checking for diverted missing values
df.loc[df['diverted']==1].isna().sum().sort_values(ascending=False)

actual_elapsed_time    2359
air_time               2359
arrived_early          2359
arrived_late           2359
arr_delay              2359
departed_early         1377
departed_late          1074
arr_time                221
wheels_on               220
taxi_in                 219
op_carrier_fl_num         0
op_unique_carrier         0
fl_date                   0
day_of_week               0
day_of_month              0
month                     0
origin_city_name          0
origin                    0
taxi_out                  0
dep_delay                 0
origin_state_nm           0
dest                      0
dest_city_name            0
dest_state_nm             0
diverted                  0
cancelled                 0
wheels_off                0
crs_arr_time              0
crs_dep_time              0
dep_time                  0
crs_elapsed_time          0
distance                  0
security_delay            0
nas_delay                 0
weather_delay             0
carrier_delay             0
late_aircraft_delay       0
route                     0
arrival_status            0
departure_status          0
dtype: int64

In [53]:
df[(df['arr_time'].isna()) & (df['cancelled']==0) & (df['diverted']==0)][['arr_time','cancelled','diverted']].shape

(0, 3)

In [54]:
df.to_csv("flight_cleaned.csv", index=False)

In [55]:
# extracting hours to check for scheduled dep hour
df['scheduled_dep_hour'] = df['crs_dep_time'].dt.hour

In [56]:
df['scheduled_dep_hour'].value_counts().sort_index()

scheduled_dep_hour
0      1769
1       517
2       230
3       143
4        63
5     28180
6     70078
7     69635
8     67997
9     56020
10    62535
11    62062
12    59483
13    59783
14    57548
15    57295
16    57852
17    62431
18    61456
19    54813
20    44928
21    33403
22    23531
23     8248
Name: count, dtype: int64

In [64]:
print(df['actual_dep_hour'].dtype)

float64

In [65]:
df['actual_dep_hour'] = df['actual_dep_hour'].astype('Int64')

In [66]:
df['actual_dep_hour'].dtype

Int64Dtype()

In [67]:
# extracting hour to check actual dep hour
df['actual_dep_hour'] = df['dep_time'].dt.hour

In [68]:
df['actual_dep_hour'].value_counts().sort_index()

actual_dep_hour
0.0      4704
1.0      1662
2.0       556
3.0       224
4.0      4276
5.0     42160
6.0     62079
7.0     60232
8.0     63163
9.0     54433
10.0    60064
11.0    58809
12.0    57822
13.0    57770
14.0    54978
15.0    56264
16.0    56347
17.0    58992
18.0    58612
19.0    53120
20.0    46501
21.0    35877
22.0    25921
23.0    12360
Name: count, dtype: int64

In [69]:
# created a weekend flag
df['is_weekend'] = np.where(
    df['day_of_week'].isin([6,7]),
    1,
    0
)

In [70]:
df['is_weekend'].value_counts()

is_weekend
0    723397
1    276603
Name: count, dtype: int64

In [71]:
categorical_cols = [
    'op_unique_carrier',
    'origin',
    'dest',
    'route',
    'arrival_status',
    'departure_status'
]

for col in categorical_cols:
    print(col, ":", df[col].nunique())

op_unique_carrier : 15
origin : 348
dest : 348
route : 6588
arrival_status : 5
departure_status : 5

In [72]:
df.to_csv("flight_cleaned_for_visualization.csv", index=False)